apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
      matchLabels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/name: traefik
  namespaceSelector:
    any: true
  endpoints:
    - targetPort: 9000
      path: /metrics
